### ISSUE TITLE
FixClient driver doesn't offer an option to pass the FIX version

### ISSUE THREAD

**Issue by francoisverbeek** [Morgan-Stanley/testplan#129]
which means regardless of spec being selected, it always passes FIX.4.2 downstream. Happy to provide a PR for a fix, but wanted to raise first.

**Comment by JohnChiotis** [comment]
Hey you are right. We can quickly add a ConfigOption in
https://github.com/Morgan-Stanley/testplan/blob/master/testplan/testing/multitest/driver/fix/client.py#L163
to pass the 'version' to the underlying fix client utility 
https://github.com/Morgan-Stanley/testplan/blob/master/testplan/common/utils/sockets/fix/client.py#L16

Would that be enough?

But maybe the underlying utility should be also a config option to driver. Currently is hardcoded
from testplan.common.utils.sockets.fix.client import Client
so you could subclass and alter them if needed.

**Comment by francoisverbeek** [comment]
either approach is good for me -- I had ``ConfigOption`` in mind as the version is already a constructor argument, but passing the class and subclassing would work too.

**Comment by francoisverbeek** [comment]
thank you!

**Comment by francoisverbeek** [comment]
fixed in https://github.com/Morgan-Stanley/testplan/pull/131
