### ISSUE TITLE
install-testplan-ui installed in virtualenv fails to find the TESTPLAN_UI_DIR

### ISSUE THREAD

**Issue by francoisverbeek** [Morgan-Stanley/testplan#135]
when installing testplan's UI in a virtual environment using ``pip install <testplan url>`` and then attempting to run ``install-testplan-ui``; ``TESTPLAN_UI_DIR`` evaluates to ``venvroot/bin/testplan/web_ui/testing`` or ``venvroot\scripts\testplan\web_ui\testing``. They don't exist when set up that way.

Running install-testplan-ui from the unzipped package source root directory does work, however.

**Comment by lambchr** [comment]
Thanks Francois, I'll take a look into this.

**Comment by lambchr** [comment]
Hi Francois,

Sorry for the delay, I have [a fix for this](https://github.com/Morgan-Stanley/testplan/commit/ba5a390dd53e525cc626591e4152482c62f18169). The install script no longer relies on a fixed directory, it finds the correct directory from testplan modules.

I'm going to close the issue but feel free to reopen or raise a new issue if you come across them.

Cheers,
Chris

**Comment by francoisverbeek** [comment]
thanks a lot, I'll have a shot at it straight away and confirm.

**Comment by francoisverbeek** [comment]
Hi Chris, I can build and launch 'npm run start', thank you. I had to upgrade a couple of dependencies to run against our internal npm repo's versions, will also experiment on my home machine to confirm in an open setup. Trying to figure out how to hook it up to `testplan -i` now :-)
