### ISSUE TITLE
roadmap and restapi test support

### ISSUE THREAD

**Issue by dkdndes** [Morgan-Stanley/testplan#144]
Hello, I would like to ask if you might provide a (feature) "Roadmap.md". And do you plan to support OpenApi endpoints with JSON payloads or is it already possible, and I didn't see it? We work on an Open Bank API Project, and I check if we could make use of your test framework in this context, too.

**Comment by JohnChiotis** [comment]
Hi. The roadmap for the project changes dynamically as per internal requirements so I am not sure we
could maintain an updated version. The idea with this repo is that you could use it an build your extensions on top of it on your fork.

There is a section in documentation explaining how to write custom drivers:
https://testplan.readthedocs.io/en/latest/multitest.html#multitest-custom-drivers

I guess you could build and maintain these endpoints on your side without having to go through all the approval/quality checks process etc.

If you have something working you can then raise an issue (like the one you did) and discuss possible adaptation by the main repo.

**Comment by dkdndes** [comment]
Thank you for the quick feedback!
