### ISSUE TITLE
LogMatcher looks like it might be very slow with large log files.

### ISSUE THREAD

**Issue by KenGordon** [Morgan-Stanley/testplan#162]
Hi Ken,

I’m not quite sure why the tell/seek mechanism has been abandoned in favour of reading the entire file into memory, but I agree it seems quite inefficient for large log files. Possibly we can optimize this by porting the old mechanism over.

Feel free to raise an issue on the github repo for this. Not sure how soon we would get around to looking at it exactly, but if you want to change it yourself we’d appreciate a PR!

Thanks,
Ryan 

-----

I seem to remember that it was possible to push stuff into some process under test and kind of stay in lockstep by waiting for the process log to be updated. I think some of our sniffer tests did that.

Trying to set up something similar I noticed that this version of LogMatcher appears to re-read the entire log file each time a match is attempted. I see it keeps a line number so the next match is the next match but it is expensive. A bit of ftell/fseek might save a lot of time and memory for large logs.

class LogMatcher(object):
    """
    Single line matcher for text files (usually log files). Once matched, it
    remembers the line number of the match and subsequent matches are scanned
    from the current line number. This can be useful when matched lines are not
    unique for the entire log file.
    """

    def __init__(self, log_path):
        """
        :param log_path: Path to the log file.
        :type log_path: ``str``
        """

        self.log_path = log_path
        self.line_no = 0

    def match(self, regex):
        """
        Matches each line in the log file from the current line number to the
        end of the file. If a match is found the line number is stored and the
        match is returned. If no match is found an Exception is raised.

        :param regex: compiled regular expression (``re.compile``)
        :type regex: ``re.Pattern``

        :return: The regex match or raise an Exception if no match is found.
        :rtype: ``re.Match``
        """
        with open(self.log_path, 'r') as log:
            lines = log.readlines()
            for line_no, line in enumerate(lines[self.line_no:], self.line_no):
                match = regex.match(line)
                if match:
                    self.line_no = line_no + 1
                    return match

        raise ValueError('No matches found')

**Comment by lambchr** [comment]
I'll change this to use the seek/tell mechanism. Thanks for raising it Ken.

**Comment by lambchr** [comment]
I've changed the LogMatcher to read a single line at a time, thanks again for raising the issue Ken.
