### ISSUE TITLE
Interactive mode broken

### ISSUE THREAD

**Issue by dobragab** [Morgan-Stanley/testplan#267]
[This example](https://testplan.readthedocs.io/en/latest/introduction.html#code) runs fine with `python test_plan.py -v` but it fails in interactive mode (after adding it in testplan decorator, as it didn't work with command line) with the following HTTP error:

# Error response
Error code 501.
Message: Unsupported method ('GET').
Error code explanation: 501 = Server does not support this operation.

Logs:

```
WARNING: Command line argument for "file_log_level" will be overridden by the one programmatically defined in Testplan[972fd3a3-afd9-404d-840b-eee838cd1627] constructor
WARNING: Command line argument for "shuffle_seed" will be overridden by the one programmatically defined in Testplan[972fd3a3-afd9-404d-840b-eee838cd1627] constructor
WARNING: Command line argument for "interactive" will be overridden by the one programmatically defined in Testplan[972fd3a3-afd9-404d-840b-eee838cd1627] constructor
Starting TestRunner[Multiply] in interactive mode
Starting TestRunnerIHandler for TestRunner[Multiply]
TestRunnerHTTPHandler listening on: 127.0.0.1:58274
127.0.0.1 - - [03/Sep/2019 13:31:48] code 501, message Unsupported method ('GET')
127.0.0.1 - - [03/Sep/2019 13:31:48] "GET / HTTP/1.1" 501 -
127.0.0.1 - - [03/Sep/2019 13:31:48] code 501, message Unsupported method ('GET')
127.0.0.1 - - [03/Sep/2019 13:31:48] "GET /favicon.ico HTTP/1.1" 501 -
```

The same happens for other examples, even interactive.Basic example.

**Comment by ryan-collingham** [comment]
Hi, thanks for trying out Testplan and reporting this issue. The interactive mode is currently a work-in-progress and quite a lot of it is not yet implemented, which is why you are getting that error message. We should note that in the docs and probably remove the interactive option from the command-line until it is fully implemented.

**Comment by ryan-collingham** [comment]
To give some more information - currently when using the interactive mode only the backend HTTP API server is started, which allows a client to control a Testplan interactively by starting/stopping test environments and running particular testcases or suites. We are in the process of implementing a new front-end web page that will consume that API and allow you to control environments and run testcases interactively by clicking appropriate parts. Watch this space!

The interactive API is designed to not be tightly coupled to our web front-end (it follows the RESTful design pattern), such that it can be consumed by alternative clients. So, for example, you could have a client written in Java that allows you to control Testplan environments from within Java code. We have examples of such usage in our docs: https://testplan.readthedocs.io/en/latest/download/Interactive.html

**Comment by dobragab** [comment]
Hi! Looking forward to the new web implementation. I swear saw something like that at a big firm 😉, and it really boosted the usefulness of the framework.

**Comment by ryan-collingham** [comment]
Great, yes the OSS interactive mode will work similar to what you may be already used to, but rewritten to fit with the new UI style (see --ui option for how this looks for static reports).

I've updated the docs (https://testplan.readthedocs.io/en/latest/download/Interactive.html) + console log message to make it clearer that only the backend API access is currently implemented.
