### ISSUE TITLE
RunnableManager is useless on its own

### ISSUE THREAD

**Issue by dobragab** [Morgan-Stanley/testplan#294]
I would think that RunnableManager can get an object derived from `Runnable` and run it. However, that is far from true, RunnableManager is intended to be used like

* Create a config class derived from `RunnableManagerConfig`, including `ConfigOption('runnable'): is_subclass(Runnable)`
* Create your class derived from `RunnableManager` with config class of your config

Then this piece of code in `RunnableManager` creates your `Runnable` instance from the `__init__` of RunnableManager` (?!):

```py
    def _initialize_runnable(self, **options):
        runnable_class = self._cfg.runnable
        runnable_config = dict(**options)
        return runnable_class(**runnable_config)
```

Meaning that your derived `Runnable` must have the same config options as `RunnableManager` (?!), including `runnable` option, which is completely useless. 

The initialization of the runnable happens in the init, I can't see why it is deferred and hidden. Instead, the RunnableManager API should look like this:

```py
  runnable = YourRunnable(**args)
  FeasibleRunnableManager(runnable=runnable).run()
```

Which is not hard to achieve, but this should be the default implementation.

```py
class FeasibleRunnableManagerConfig(RunnableManagerConfig):
  @classmethod
  def get_options(cls):
      return {
        ConfigOption('runnable'): lambda obj: isinstance(obj, Runnable),
      }

class FeasibleRunnableManager(RunnableManager):
  CONFIG = FeasibleRunnableManagerConfig
  def _initialize_runnable(self, **options):
    return self._cfg.runnable
```

**Comment by ryan-collingham** [comment]
Hi, thanks for raising this issue. RunnableManager is a abstract base class and an internal implementation detail of Testplan, it is not  intended to be exposed as part of the package's public API for use by code outside of Testplan itself.
