### ISSUE TITLE
WebServerExporter should be able to display an existing JSON

### ISSUE THREAD

**Issue by dobragab** [Morgan-Stanley/testplan#295]
The `WebServerExporter.export` does two things: exporting the JSON and then starting a web server that will open that JSON.

If these two things are separated to two functions, we can use WebServerExporter to display a JSON that already exists, either as a standalone app or a custom test_plan. It is extremely useful to view reports generated by CI.

Required changes are small, see https://github.com/Morgan-Stanley/testplan/compare/master...dobragab:webserver-display

**Comment by ryan-collingham** [comment]
Yes it would be a useful enhancement to be able to view existing JSON reports from file. Your linked change looks good to me - if you want to raise a PR we can look at mering it in. Thanks!

**Comment by dobragab** [comment]
Merged in #305.
