### ISSUE TITLE
Interactive mode doesn't call after_start

### ISSUE THREAD

**Issue by dobragab** [Morgan-Stanley/testplan#380]
When MultiTest's constructor is given an `after_start` callable, that is called only if run from command line, not if the environment is started after a click on the UI.

**Comment by ryan-collingham** [comment]
Hi, thanks for reporting this issue. We have not yet implemented integration of before/after_start callables to the interactive mode, but we can look at adding it soon.

**Comment by ryan-collingham** [comment]
Should now be fixed - our own examples that use after_start work fine in interactive mode now.
