### ISSUE TITLE
How does interactive reload work?

### ISSUE THREAD

**Issue by dobragab** [Morgan-Stanley/testplan#426]
I saw there's an interactive reloader class, with a [corresponding test](https://github.com/Morgan-Stanley/testplan/blob/master/tests/functional/testplan/runnable/interactive/interactive_executable.py). 

However, I couldn't make it work in a real world example. Expected:

1. start the interactive environment
2. run a test, fails a simple assertion like `result.equal(5, 2+2)` 
3. change the test code to fix it
4. click some button on the interactive UI
5. run the test again, now it passes

I tried adding a dummy testcase that calls `plan.i.reload()` as a substitution for step 4, but it didn't work.

**Comment by ryanc414** [comment]
FYI, interactive reload was partially implemented on the backend but was never properly linked to the UI. To make it work in the UI you would either need to:

1. Expose a reload endpoint over the interactive API and have the UI call it (either periodically, or when a reload button is clicked in the UI)

or

2. Have the backend automatically call reload, either periodically or triggered by certain actions (e.g. before running a test).

The second option is probably simplest. Bear in mind that reload() is potentially an expensive call for projects with a lot of test files, particularly if those test files are on a network file system.

**Comment by ryanc414** [comment]
IMO the ideal solution would be a mix of the two, have some inotify-based file watcher on the backend that monitors file changes and automatically reloads, but also have a button in the UI to trigger a manual reload for platforms that don't support inotify or for changes that inotify cannot detect (e.g. changes made from another host to files on a network mount).

**Comment by dobragab** [comment]
I guess #547 answers this.
