### ISSUE TITLE
How to add testcase into testsuite programtical

### ISSUE THREAD

**Issue by zhboseu** [Morgan-Stanley/testplan#46]
Dear there,
Our test cases are created dynamically from external conditions and constraints, it is difficult to code all of the testcases function beforehand.

How to create a testcase through _API_? not use `@testcase` to annotate member function.
And add testcase into testsuite programtical?

Thanks for your attention.

**Comment by kelliott55** [comment]
Hello zhboseu,
Thanks for your question.
Have a look at the Parameterization feature: http://testplan.readthedocs.io/en/latest/multitest.html#parametrization 
You'll be able to load your external data conditions and then testplan will pass them to the testcase as parameters.
Also just a note, Issues are for bugs/features, for general questions please contact the group via the project email "eti-testplan@morganstanley.com", thanks.
