### ISSUE TITLE
FixServer misleading error message

### ISSUE THREAD

**Issue by francoisverbeek** [Morgan-Stanley/testplan#460]
in `testplan/common/utils/sockets/fix/server.py:451` the error message states 'there are more connections active' also when there is 0 connection active. 
Ideally should say 'more or no connections active' or even better have 3 cases 0, 1 and more.
Happy to provide a pull request if you would like one :-)

**Comment by Pyifan** [comment]
Hi Francois, welcome back! Let me fix this one real quick :)
Thanks for pointing it out!

**Comment by francoisverbeek** [comment]
Thanks a lot!
