### ISSUE TITLE
install-testplan-ui raises exception on MacOS Catalina

### ISSUE THREAD

**Issue by NautillusSs** [Morgan-Stanley/testplan#516]
The virtualenv install on MacOS raises an exception:

```
  File "/Users/blah/projectName/test/functional/testplan-oss/lib/python3.8/site-packages/testplan/runners/pools/remote.py", line 668, in RemotePoolConfig
    default_hostname = socket.gethostbyname(socket.gethostname())
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

I fixed it by specifying "localhost" instead of the gethostname() method:

```
--- a/testplan/runners/pools/remote.py
+++ b/testplan/runners/pools/remote.py
@@ -665,7 +665,10 @@ class RemotePoolConfig(PoolConfig):
     resource entity.
     """

-    default_hostname = socket.gethostbyname(socket.gethostname())
+    if sys.platform == "darwin":
+        default_hostname = socket.gethostbyname("localhost")
+    else:
+        default_hostname = socket.gethostbyname(socket.gethostname())
     default_workspace_root = workspace_root()

     @classmethod
```

[solution reference](https://stackoverflow.com/questions/39970606/gaierror-errno-8-nodename-nor-servname-provided-or-not-known-with-macos-sie)

Should I raise a PR or can you update the code? Thanks.

**Comment by dcm** [comment]
Hi @NautillusSs, can you confirm your `/etc/hosts` contains (at least) this?

```
127.0.0.1	localhost
```

I can only elicit your error when I empty my `/etc/hosts` and restart networking:

```
$ python2 <<EOF
import socket as s

print(s.gethostbyname(s.gethostname()))
print(s.gethostbyname("localhost"))

EOF
127.0.0.1
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

$ python3 <<EOF
import socket as s

print(s.gethostbyname(s.gethostname()))
print(s.gethostbyname("localhost"))

EOF
127.0.0.1
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by dcm** [comment]
Still this looks like a system problem since I can run `socket.gethostbyname(socket.gethostname())` without an issue on Catalina. What version are you on?

Just for future reference I had a look at the CPython src, nothing jumps out as the cause however.

* [socket_gethostbyname](https://github.com/python/cpython/blob/v3.7.5/Modules/socketmodule.c#L5250)
* [socket_getaddrinfo](https://github.com/python/cpython/blob/v3.7.5/Modules/socketmodule.c#L6199)
* [setipaddr](https://github.com/python/cpython/blob/v3.7.5/Modules/socketmodule.c#L1033)

**Comment by dcm** [comment]
Can you also check if `/private/etc/hosts` contains the `127.0.0.1  localhost` line?

**Comment by NautillusSs** [comment]
Hi @dcm,
Version: 10.15.7
/private/etc/hosts also contains that line.

**Comment by NautillusSs** [comment]
Hi,

I solved it by adding the host value stored in $HOST to my /etc/hosts.
```
127.0.0.1   Ns-MacBook-Pro.local
```
