### ISSUE TITLE
log matcher support

### ISSUE THREAD

**Issue by Splanzar** [Morgan-Stanley/testplan#52]
Hi team,
I was a morganer before, I remembered there was a very useful feature called log matcher when I used it, but I could not find it in this version
Do you have plans to add it, or has it been changed to other equivalent stuff?

Thanks,
Tai

**Comment by JohnChiotis** [comment]
We can port it over! I think so far was not needed but it could be useful.

**Comment by lambchr** [comment]
Hi @Splanzar,

We've added a very simple [LogMatcher utility](https://github.com/Morgan-Stanley/testplan/blob/master/testplan/common/utils/match.py#L38-L75). It doesn't include any timeout logic or the ability to mark at a certain location. I recommend that you use the LogMatcher with the timing utility [retry_until_timeout](https://github.com/Morgan-Stanley/testplan/blob/master/testplan/common/utils/timing.py#L179-L207) if you want retry until a particular timeout.

```
from testplan.common.utils.match import LogMatcher 
from testplan.common.utils.timing import retry_until_timeout

# path is defined by you
matcher = LogMatcher(log_path=path)
# timeout, regex_expression & interval is defined by you
match = retry_until_timeout(
    exception=ValueError,
    item=matcher.match,
    timeout=timeout,
    kwargs={'regex': regex_expression},
    interval=interval,
    raise_on_timeout=True
)
```

I'll close the issue for now, if this doesn't solve your issue or you would like the marking feature please reopen the issue.

### Mark Feature
This is just a brief explanation of the mark feature. The marking feature allowed you to mark the current position with a particular name and then later use seek to make LogMatcher search from that marked position.

```
# matcher will find the line that matches the regex expression and save its position in matcher.position
matcher.match(regex=regex_expression)
# calling mark with a name will save this position to be used later
matcher.mark(name='first match')
...
# we can then do other matches which will move matcher.position to different values
# calling seek will put the position back to the marked position with the same name
# LogMatcher will then search from this position
matcher.seek(mark='first match')
```

**Comment by lambchr** [comment]
Just a note, #162 required us to change LogMatcher. There is now no need to called it with retry_until_timeout, you can just specify a timeout when calling the match method.

```
matcher = LogMatcher(log_path=path)
matcher.match(regex=regex_expression, timeout=timeout)
```

**Comment by Splanzar** [comment]
Thanks a lot!
