### ISSUE TITLE
install testplan ui fails with not-very-clear error message

### ISSUE THREAD

**Issue by francoisverbeek** [Morgan-Stanley/testplan#525]
### Description

Hi everyone, how are you doing?

How to install the ui is not very well documented (minimum requirements for instance). It was relatively easy to find out I needed yarn and pegjs but still after that `install-testplan-ui` doesn't work as expected. I suspect I may just be running unsupported versions (in debian 10.5 and RHEL 6).

Note that a version of tesptlan I downloaded on June 23, 2020 can be installed with the same node/yarn setup, but then I have another issue where some missing keys in dictmatch would lead the js to crash and I wanted to try with a more recent version to see whether it may have been solved before filing an issue for that one.

### Steps to Reproduce

```
(venv) frans@nas:~$python3 -m venv
(venv) frans@nas:~$source venv/bin/activate
(venv) frans@nas:~$git clone https://github.com/Morgan-Stanley/testplan.git
(venv) frans@nas:~$sudo apt-get install npm
(venv) frans@nas:~$sudo npm install -g yarn

(venv) frans@nas:~$ node --version
v10.21.0

(venv) frans@nas:~$ install-testplan-ui
INFO:Installing Testplan UI dependencies...
INFO:Installing to path: /data/frans/home/venv/lib/python3.7/site-packages/testplan/web_ui/testing
INFO:Building Testplan UI...
Traceback (most recent call last):
  File "/data/frans/home/venv/bin/install-testplan-ui", line 117, in <module>
    install_and_build_ui(path=args.path, dev=args.dev, verbose=args.verbose)
  File "/data/frans/home/venv/bin/install-testplan-ui", line 110, in install_and_build_ui
    stderr=subprocess.STDOUT,
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'yarn run build' returned non-zero exit status 127.

(venv) frans@nas:~$sudo npm install -g pegjs
...
(venv) frans@nas:~$ install-testplan-ui
INFO:Installing Testplan UI dependencies...
INFO:Installing to path: /data/frans/home/venv/lib/python3.7/site-packages/testplan/web_ui/testing
INFO:Building Testplan UI...
Traceback (most recent call last):
  File "/data/frans/home/venv/bin/install-testplan-ui", line 117, in <module>
    install_and_build_ui(path=args.path, dev=args.dev, verbose=args.verbose)
  File "/data/frans/home/venv/bin/install-testplan-ui", line 110, in install_and_build_ui
    stderr=subprocess.STDOUT,
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'yarn run build' returned non-zero exit status 1.
(venv) frans@nas:~$ cd venv/lib/python3.7/site-packages/testplan/web_ui/testing/
(venv) frans@nas:~/venv/lib/python3.7/site-packages/testplan/web_ui/testing$
(venv) frans@nas:~/venv/lib/python3.7/site-packages/testplan/web_ui/testing$ /usr/local/bin/yarn run build
yarn run v1.22.10
$ pegjs --format es src/Parser/SearchFieldParser.pegjs
Module format must be one of "amd", "commonjs", "globals", and "umd".
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

(venv) frans@nas:~/venv/lib/python3.7/site-packages/testplan/web_ui/testing$ cat /etc/debian_version
10.5
(venv) frans@nas:~/venv/lib/python3.7/site-packages/testplan/web_ui/testing$ pegjs --version
PEG.js 0.10.0


```

**Expected behavior:**

Either something that says that my dependencies are wrong, or something along these lines; or a successful install

**Actual behavior:**

not very clear error message

### Software

- **PEG.js:** 0.10.0
- **Node.js:** 10.210
- **NPM or Yarn:** npm 5.8.0
- **Browser:** N/A
- **OS:** Linux debian 10.5
- **Editor:** vi

**Comment by yuxuan-ms** [comment]
Hi @francoisverbeek  " Command 'yarn run build' returned non-zero exit status 127." means that the script cannot find "yarn" command. "install-testplan-ui" has migrated from NPM to Yarn. Please follow https://classic.yarnpkg.com/en/docs/install/ to install Yarn.

**Comment by francoisverbeek** [comment]
Hi @yuxuan-ms, I have done so; the 127 (file not found) is actually for pegjs. I have also installed pegjs; I get exit code 1 afterwards, which is caused by pegjs complaining about format not being one of 'amd', 'commonjs', 'global's or 'umd'.  I've included the output in the trace. Also happy to produce a PR for updating the doc about the requirement to install yarn and/or pegjs, but before I do so wanted to share this issue, and to discuss what whether it's related to npm or other dependency versions or just a wrong invocation?

**Comment by kn-ms** [comment]
Hi @francoisverbeek you need pegjs: 0.11.0-master.b7b87ea as the 0.10 could not generate es6 import compatible package. I will take a look, why the install script do not install pegjs, it is in dev dependencies.

**Comment by kn-ms** [comment]
pegjs should not be a dev dependency, as all stuff needed to build the project is in dependencies, as that is used for the install. I will open a pull request with that, till that you can use the --dev switch to install_testplan_ui

**Comment by francoisverbeek** [comment]
thanks, updating to using explicitly pegjs@0.11.0-master.b7b87ea I can get it through ok.
